language: python
python:
    - "3.4"
before_install:
    - pip install pytest pytest-runner pytest-cov
install:
    - python setup.py install
script:
    - py.test
    - py.test --cov-report= --cov=wca_api tests/
after_success:
    - coveralls